apiVersion: v1
kind: Secret
metadata:
  name: keda-redis-secret
  namespace: wordpress-staging
  labels:
    app: wp-k8s-service
type: Opaque
stringData:
  # Redis password for Dramatiq broker
  password: "dramatiq-broker-password"
