apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress-staging

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: wp-k8s-service
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: wordpress-clone-system
