apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-k8s-service
  namespace: wordpress-staging
  annotations:
    # IRSA annotation for AWS permissions (EKS, RDS, etc.)
    eks.amazonaws.com/role-arn: arn:aws:iam::044514005641:role/wp-clone-restore-wp-k8s-service
