version: "3"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: observability_loki
    user: "0:0"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: observability_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # User can change this later
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: observability_tempo
    user: "0:0"
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./tempo-config.yml:/etc/tempo/tempo.yaml
      - tempo_data:/tmp/tempo
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: observability_alloy
    ports:
      - "12345:12345"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy
    restart: unless-stopped

volumes:
  loki_data:
  tempo_data:
  alloy_data:
  grafana_data:
